"""HTML single-file report with indented tree visualisation."""
from __future__ import annotations

import logging
from html import escape
from pathlib import Path

from tree_size.core.formatter import fmt_size
from tree_size.core.node import Node

logger = logging.getLogger(__name__)

# Number of non-breaking spaces per indentation level.
_INDENT_WIDTH = 4


class HtmlExporter:
    """Write a Node tree as a self-contained HTML report.

    The report uses only inline CSS — no external assets — so the file is
    fully portable.
    """

    def export(self, root: Node, dest: Path) -> None:
        """Write *root* and its subtree to *dest* as a UTF-8 HTML file.

        Args:
            root: The top-level node.
            dest: Output file path.  Created or overwritten.

        Raises:
            OSError: If the file cannot be opened for writing.
        """
        html = self._render(root)
        with open(dest, "w", encoding="utf-8") as f:
            f.write(html)

        logger.info("HTML export completed: %s", dest)

    # ------------------------------------------------------------------
    # Rendering helpers
    # ------------------------------------------------------------------

    def _render(self, root: Node) -> str:
        """Return the complete HTML document as a string."""
        table_html = self._build_table(root)
        return (
            "<!DOCTYPE html>\n"
            "<html>\n"
            "<head>\n"
            '  <meta charset="UTF-8">\n'
            f"  <title>Tree-Size Report: {escape(root.name)}</title>\n"
            "  <style>\n"
            "    body { font-family: Arial, sans-serif; margin: 20px;"
            " background: #f5f5f5; }\n"
            "    h1 { color: #333; }\n"
            "    table { border-collapse: collapse; width: 100%;"
            " background: white; }\n"
            "    th { background: #007bff; color: white; padding: 8px;"
            " text-align: left; }\n"
            "    td { border-bottom: 1px solid #ddd; padding: 8px; }\n"
            "    tr:hover { background: #f9f9f9; }\n"
            "    .size { text-align: right; }\n"
            "  </style>\n"
            "</head>\n"
            "<body>\n"
            f"  <h1>Disk Usage Report: {escape(root.name)}</h1>\n"
            f"  <p><strong>Root:</strong> {escape(str(root.path))}</p>\n"
            f"  <p><strong>Total Size:</strong> {fmt_size(root.size_logical)}</p>\n"
            f"  <p><strong>Files:</strong> {root.file_count},"
            f" <strong>Folders:</strong> {root.folder_count}</p>\n"
            f"\n{table_html}\n\n"
            "  <hr>\n"
            "  <p><small>Generated by Tree-Size</small></p>\n"
            "</body>\n"
            "</html>"
        )

    def _build_table(self, root: Node) -> str:
        """Return an HTML table string for *root* and all descendants."""
        rows: list[str] = [
            "  <table>",
            "    <tr>",
            "      <th>Name</th>",
            "      <th class=\"size\">Size</th>",
            "      <th class=\"size\">Files</th>",
            "      <th class=\"size\">Folders</th>",
            "    </tr>",
        ]
        self._append_rows(root, depth=0, rows=rows)
        rows.append("  </table>")
        return "\n".join(rows)

    def _append_rows(self, node: Node, depth: int, rows: list[str]) -> None:
        """Append <tr> elements for *node* and its descendants to *rows*."""
        indent = "&nbsp;" * (depth * _INDENT_WIDTH)
        rows.append(
            "    <tr>"
            f"<td>{indent}{escape(node.name)}</td>"
            f'<td class="size">{fmt_size(node.size_logical)}</td>'
            f'<td class="size">{node.file_count}</td>'
            f'<td class="size">{node.folder_count}</td>'
            "</tr>"
        )
        for child in node.children:
            self._append_rows(child, depth + 1, rows)
